# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.2.19-cli-node

    steps:
      - checkout

      - run: composer global require --no-update drupal/coder

      - restore_cache:
          keys:
          # "composer.lock" can be used if it is committed to the repo
          - v1-dependencies-{{ checksum "~/.composer/composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer global install

      - save_cache:
          key: v1-dependencies-{{ checksum "~/.composer/composer.json" }}
          paths:
            - ~/.composer/vendor

      - run:
          command: |
            export PATH="$PATH:$HOME/.composer/vendor/bin"
            phpcs --config-set installed_paths ~/.composer/vendor/drupal/coder/coder_sniffer
            git diff-tree --no-commit-id --name-only -r HEAD | xargs phpcs --standard=Drupal --extensions=php,inc,module
            env

#      - restore_cache:
#          keys:
#            - node-v1-{{ checksum "package.json" }}
#            - node-v1-
#      - run: yarn install
#      - save_cache:
#          key: node-v1-{{ checksum "package.json" }}
#          paths:
#            - node_modules

      # run tests with phpunit or codecept
#      - run: ./vendor/bin/phpunit --log-junit test-results/phpunit/results.xml
#      - run: ./vendor/bin/codecept build
#      - run: ./vendor/bin/codecept run

#      - store_test_results:
#          path: test-results
