# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.2.19-cli-node

    steps:
      - checkout

      - run: composer global require --no-update drupal/coder

      - restore_cache:
          keys:
          # "composer.lock" can be used if it is committed to the repo
          - v1-dependencies-{{ checksum "~/.composer/composer.json" }}

      - run: composer global install

      - save_cache:
          key: v1-dependencies-{{ checksum "~/.composer/composer.json" }}
          paths:
            - ~/.composer/vendor

      - run:
          command: |
            export PATH="$PATH:$HOME/.composer/vendor/bin"
            phpcs --config-set installed_paths ~/.composer/vendor/drupal/coder/coder_sniffer
            BASE=$(php ./.circleci/get_pull_request_target_branch.php --api-user $GithubApiUser --api-token $GithubApiToken)
            git checkout -q $BASE
            git reset --hard -q origin/$BASE
            git checkout -q $CIRCLE_BRANCH
            git --no-pager diff-tree --no-commit-id --name-only -r $BASE..HEAD | xargs phpcs --standard=Drupal --extensions=php,inc,module
